### ISSUE TITLE
`gmail.send` exception handling broken in Python 3

### ISSUE THREAD

**Issue by sdeleon28** [paulchakravarti/gmail-sender#7]
Tried sending an email with this snippet:

```
gmail = GMail('Me <me@gmail.com>', 'password')
msg = Message('Test Message', to='Me <me@gmail.com>', text='Hello')
gmail.send(msg)
```

Delivery failed but an error with `<bytes>.startswith` masks the actual exception. This is the traceback that comes up:

```
Traceback (most recent call last):
  File "./send_email.py", line 8, in <module>
    gmail.send(msg)
  File "/path/to/project/lib/python3.4/site-packages/gmail/gmail.py", line 91, in send
    self.connect()
  File "/path/to/project/lib/python3.4/site-packages/gmail/gmail.py", line 76, in connect
    if e.smtp_error.startswith("5.7.14"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by paulchakravarti** [comment]
Thanks for spotting this - it turns out the SMTPAuthenticationError.smtp_error is a string in Python 2 and bytes in Python 3. I can't actually trigger the exception that I was trying to catch here any more and suspect that Gmail now requires application passwords for all SMTP use so have just removed this check and pass through the SMTPAuthenticationError directly (and have updated the docs to note that an app password is required). Have uploaded new version to PyPi (0.6.2)

**Comment by sdeleon28** [comment]
Thanks for addressing this so quickly. I actually was able to reproduce the bug reliably. The exception was happening because I didn't have the option to [allow less secure apps](https://support.google.com/accounts/answer/6010255?hl=en) enabled, so you might still want to handle this case gracefully.

**Comment by paulchakravarti** [comment]
Did the fix work even with this disabled (and do you get a sensible error message) - I can test as the setting isn't available if 2FA is enabled which is why I assumed that it had been deprecated (and app specific passwords were required - which to be honest seems more sensible). Hopefully the SMTP error message should be ok as it doesn't seem sensible continuing to try to wrap these.

`This setting is not available for accounts with 2-Step Verification enabled. Such accounts require an application-specific password for less secure apps access. Learn more`
